import { buildSearchText } from '@/lib/search';
import type { ModelView, OfferView, PageData, ProviderRef } from '@/lib/view';

/**
 * A small hand-built catalogue for the WebMCP tests.
 *
 * Deliberately not `data/prices.json`: that file is regenerated by the refresh
 * job, so asserting exact prices against it would make the suite fail for
 * reasons that have nothing to do with this code.
 */

const OBSERVED_AT = '2026-08-26T00:00:00.000Z';

function offer(partial: Partial<OfferView> & { provider_id: string }): OfferView {
  return {
    input_usd_per_1m: null,
    output_usd_per_1m: null,
    cache_read_usd_per_1m: null,
    cache_write_usd_per_1m: null,
    discount_pct: null,
    discount_unavailable_reason: null,
    observed_at: OBSERVED_AT,
    tier: null,
    is_best: false,
    stale: false,
    ...partial,
  };
}

function model(partial: Omit<ModelView, 'search_text'> & { aliases?: string[] }): ModelView {
  const { aliases = [], ...rest } = partial;
  return {
    ...rest,
    search_text: buildSearchText([rest.display_name, rest.id, rest.maker, ...aliases]),
  };
}

export const PROVIDERS: Record<string, ProviderRef> = {
  alpha: { id: 'alpha', name: 'Alpha Relay', visit_url: 'https://alpha.example/', source_kind: 'api' },
  beta: { id: 'beta', name: 'Beta Gateway', visit_url: 'https://beta.example/', source_kind: 'html' },
  gamma: { id: 'gamma', name: 'Gamma Cheap', visit_url: 'https://gamma.example/', source_kind: 'seed' },
  delta: { id: 'delta', name: 'Delta Precision', visit_url: 'https://delta.example/', source_kind: 'api' },
};

export function buildFixture(): PageData {
  const models: ModelView[] = [
    model({
      id: 'claude-opus-5',
      display_name: 'Claude Opus 5',
      maker: 'Anthropic',
      aliases: ['opus-5', 'opus'],
      provider_count: 3,
      best_input_usd_per_1m: 2,
      best_output_usd_per_1m: 10,
      best_discount_pct: 60,
      official_baseline: {
        model_id: 'claude-opus-5',
        input_usd_per_1m: 5,
        output_usd_per_1m: 25,
        source_url: 'https://example.invalid/opus',
        verified_at: '2026-08-24',
        note: 'Fixture baseline.',
      },
      offers: [
        // Cheapest fresh offer for this model.
        offer({ provider_id: 'beta', input_usd_per_1m: 2, output_usd_per_1m: 10, discount_pct: 60, is_best: true }),
        offer({ provider_id: 'alpha', input_usd_per_1m: 5, output_usd_per_1m: 25 }),
        // Cheapest on paper, but its provider's refresh failed: must never win.
        offer({ provider_id: 'gamma', input_usd_per_1m: 0.5, output_usd_per_1m: 1, stale: true }),
      ],
    }),
    model({
      id: 'gpt-5.6-sol',
      display_name: 'GPT-5.6 Sol',
      maker: 'OpenAI',
      aliases: ['gpt 5.6 sol'],
      provider_count: 2,
      best_input_usd_per_1m: 1,
      best_output_usd_per_1m: 5,
      best_discount_pct: 75,
      official_baseline: null,
      offers: [
        offer({ provider_id: 'beta', input_usd_per_1m: 1, output_usd_per_1m: 5, discount_pct: 75, is_best: true }),
        offer({ provider_id: 'alpha', input_usd_per_1m: 4, output_usd_per_1m: 20, tier: 'thinking' }),
      ],
    }),
    model({
      id: 'tiny-model',
      display_name: 'Tiny Model',
      maker: 'TestCo',
      provider_count: 1,
      best_input_usd_per_1m: 0.1,
      best_output_usd_per_1m: 0.2,
      best_discount_pct: null,
      official_baseline: null,
      offers: [offer({ provider_id: 'alpha', input_usd_per_1m: 0.1, output_usd_per_1m: 0.2, is_best: true })],
    }),
    model({
      id: 'partial-model',
      display_name: 'Partial Model',
      maker: 'TestCo',
      provider_count: 1,
      best_input_usd_per_1m: 3,
      best_output_usd_per_1m: null,
      best_discount_pct: null,
      official_baseline: null,
      // Publishes an input price only, so it can never be costed or ranked.
      offers: [offer({ provider_id: 'alpha', input_usd_per_1m: 3, output_usd_per_1m: null })],
    }),
    model({
      id: 'precision-model',
      display_name: 'Precision Model',
      maker: 'TestCo',
      provider_count: 1,
      best_input_usd_per_1m: 1.234567,
      best_output_usd_per_1m: 0,
      best_discount_pct: null,
      official_baseline: null,
      offers: [offer({ provider_id: 'delta', input_usd_per_1m: 1.234567, output_usd_per_1m: 0, is_best: true })],
    }),
  ];

  return {
    models,
    providers: PROVIDERS,
    provider_status: [],
    generated_at: OBSERVED_AT,
    total_offers: models.reduce((sum, entry) => sum + entry.offers.length, 0),
  };
}
