import type { ProviderVerificationRecord } from './types';

/**
 * Researched provider transparency records.
 *
 * See `docs/PROVIDER_VERIFICATION.md` for the methodology and the update
 * procedure. A separate internal matrix, not published, records which providers
 * were already checked and deliberately rejected.
 *
 * The short version:
 *
 *  - A **public operator** is an accountability signal, not a company
 *    registration. A named person counts when public evidence connects them to
 *    the service — their own statement of what they run, the provider linking
 *    them, official material naming them, or a credible profile or interview.
 *  - A company named only by the provider is `self_disclosed`. `verified` needs
 *    an independent registry record *and* a reference we can link.
 *  - `strength` gates display: only `strong` and `supported` reach the screen.
 *    `weak` is recorded so a lead is not lost, and never rendered.
 *  - `opened: false` marks a source we could only read through a search index.
 *    X and LinkedIn refuse automated fetches; the drawer says so in the open.
 *  - Never turn a handle into a legal name. Never publish a name that appears
 *    only inside a mailing address.
 *
 * `transparency_level` is never written here. It is derived in `derive.ts`.
 */

/** UTC date of the review pass that produced this file. */
const REVIEWED = '2026-08-27';

/** UTC date of the frontier-gateway expansion review. */
const REVIEWED_EXPANSION = '2026-08-31';

/** UTC date of the completion pass that reproduced the registry records. */
const REVIEWED_COMPLETION = '2026-09-01';

export const VERIFICATION_RECORDS: ProviderVerificationRecord[] = [
  {
    provider_id: 'relayrouter',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'identified',
      public_name: 'Sukie',
      role: 'Operator',
      profile_urls: ['https://t.me/s/sukieai', 'https://x.com/sukie234'],
      strength: 'strong',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://relayrouter.io/',
      docs: 'https://relayrouter.io/docs',
      pricing: 'https://relayrouter.io/pricing',
      terms: 'https://relayrouter.io/terms',
      privacy: 'https://relayrouter.io/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://t.me/sukieaiplayground',
      support: 'mailto:support@relayrouter.io',
    },
    unreadable_surfaces: ['terms', 'privacy'],
    operating_history: null,
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Sukie AI Playground',
        source_name: 'Telegram group linked by the provider',
        url: 'https://t.me/s/sukieaiplayground',
        source_type: 'first_party',
        note: 'The group RelayRouter links from its own site is run under the Sukie identity, and its description gives relayrouter.io as its relay.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Sukie announcements channel',
        source_name: 'Telegram channel',
        url: 'https://t.me/s/sukieai',
        source_type: 'profile',
        note: 'Sukie’s public channel repeatedly links relayrouter.io and relaydance.com as the services she runs.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Homepage',
        source_name: 'Provider site',
        url: 'https://relayrouter.io/',
        source_type: 'first_party',
        note: 'Identifies RelayRouter as an AI API gateway and links the Telegram community as its channel.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://relayrouter.io/docs',
        source_type: 'first_party',
        note: 'Describes the single endpoint, the supported model providers and the API integrations.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'RelayRouter links a Telegram group run under the name Sukie, and that identity’s public channel gives relayrouter.io as its relay and relaydance.com as a companion video service. Sukie is a public handle rather than a legal name, and no company is named anywhere on the site.',
    unknowns: [
      'Sukie is a public handle. No legal name is published, and we did not attempt to establish one.',
      'No company or jurisdiction is named on any page.',
      'The terms and privacy pages are served but render their text in the browser, so their wording could not be read.',
      'No public connection was found between RelayRouter and the separately branded services at derouter.ai, derouter.network or github.com/derouter, which describe different products.',
    ],
  },
  {
    provider_id: 'midrelay',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'identified',
      public_name: 'Shek',
      role: 'Product manager; states he built MidRelay',
      profile_urls: ['https://dev.to/midrelay'],
      strength: 'strong',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://midrelay.com/en',
      docs: 'https://midrelay.com/en/docs',
      pricing: 'https://midrelay.com/en',
      terms: 'https://midrelay.com/en/terms',
      privacy: 'https://midrelay.com/en/privacy',
      github: null,
      x: 'https://x.com/midrelay_ai',
      linkedin: null,
      chat: 'https://t.me/midrelay',
      support: 'mailto:support@midrelay.com',
    },
    operating_history: 'Terms and privacy last updated 10 May 2026.',
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Shek on DEV',
        source_name: 'DEV profile',
        url: 'https://dev.to/midrelay',
        source_type: 'profile',
        note: 'Profile is named Shek, uses the handle midrelay, gives the work role product manager and links midrelay.com as its own site.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Article by the same author',
        source_name: 'DEV article',
        url: 'https://dev.to/midrelay/why-your-claude-api-bill-is-3x-what-it-should-be-and-how-to-fix-it-4lfo',
        source_type: 'profile',
        note: 'Author Shek writes “I built a little proxy called MidRelay”.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://midrelay.com/en/terms',
        source_type: 'first_party',
        note: 'Describes MidRelay as a reseller-grade reverse proxy operated at midrelay.com. No company is named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'privacy',
        label: 'Privacy policy',
        source_name: 'Provider Privacy',
        url: 'https://midrelay.com/en/privacy',
        source_type: 'first_party',
        note: 'States servers are located in Asia and lists the Telegram and X accounts as the provider’s own channels.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'A developer publishing as Shek states that he built MidRelay, and his profile links midrelay.com as his own site. He gives his role as product manager rather than founder. The site itself names no company and no person.',
    unknowns: [
      'Shek is the public name used on the profile; no fuller legal identity is published.',
      'midrelay.com does not link back to that profile, so the connection rests on the profile’s own claim.',
      'No company name, registered address or jurisdiction is disclosed.',
    ],
  },
  {
    provider_id: 'tokenmix',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'verified',
      name: 'Token Limited',
      jurisdiction: 'Hong Kong',
      registration_reference:
        'https://www.cr.gov.hk/docs/wrpt/RNC063_2026.03.23-2026.03.29.pdf',
      strength: 'strong',
    },
    official_presence: {
      website: 'https://tokenmix.ai/',
      docs: 'https://tokenmix.ai/docs',
      pricing: 'https://tokenmix.ai/pricing',
      terms: 'https://tokenmix.ai/terms',
      privacy: 'https://tokenmix.ai/privacy',
      github: 'https://github.com/TokenMixAi',
      x: 'https://x.com/tokenmixai',
      linkedin: null,
      chat: 'https://discord.gg/xj7ETnk4VA',
      support: null,
    },
    operating_history: 'Official GitHub account created 13 March 2026.',
    evidence: [
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'About page',
        source_name: 'Provider About',
        url: 'https://tokenmix.ai/about',
        source_type: 'first_party',
        note: 'States TokenMix is operated by Token Limited and gives Hong Kong as the founding location.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://tokenmix.ai/terms',
        source_type: 'first_party',
        note: 'States the agreement is with Token Limited, a company incorporated in Hong Kong.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Register of newly incorporated companies',
        source_name: 'Hong Kong Companies Registry',
        url: 'https://www.cr.gov.hk/docs/wrpt/RNC063_2026.03.23-2026.03.29.pdf',
        source_type: 'registry',
        note: 'The registry’s own weekly report lists Token Limited, business registration number 80068393, incorporated 26 March 2026.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'github',
        label: 'GitHub account',
        source_name: 'GitHub API record',
        url: 'https://api.github.com/users/TokenMixAi',
        source_type: 'profile',
        note: 'Account names TokenMix, gives its company as Token Limited and links tokenmix.ai. Created 13 March 2026.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Official accounts',
        source_name: 'Provider structured data',
        url: 'https://tokenmix.ai/about',
        source_type: 'first_party',
        note: 'The site’s own markup lists its X, GitHub, Discord and Telegram accounts.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'TokenMix names Token Limited, incorporated in Hong Kong, as its operating company, and the Hong Kong Companies Registry’s own incorporation report lists that company with business registration number 80068393. It is the only company in this index we could confirm against a government registry. No individual is named.',
    unknowns: [
      'The registry record establishes that Token Limited exists. That the company operates TokenMix is the provider’s own statement, not something the registry says.',
      'No founder, officer or team member is named on any surface.',
      'There is no dedicated support page; that path returns 404.',
    ],
  },
  {
    provider_id: 'cometapi',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'identified',
      public_name: 'Lee Sonic',
      role: 'CEO',
      profile_urls: ['https://sg.linkedin.com/in/lee-sonic-220155121'],
      strength: 'strong',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://www.cometapi.com/',
      docs: 'https://www.cometapi.com/quickstart/',
      pricing: 'https://www.cometapi.com/pricing/',
      terms: 'https://www.cometapi.com/terms-of-service/',
      privacy: 'https://www.cometapi.com/privacy-policy/',
      github: 'https://github.com/cometapi-dev',
      x: 'https://x.com/cometapi_ai',
      linkedin: 'https://www.linkedin.com/company/cometapi',
      chat: 'https://discord.gg/HMpuV6FCrG',
      support: 'https://www.cometapi.com/support/',
    },
    operating_history: 'Company profile gives a founding year of 2024; the GitHub organisation was created 7 August 2025.',
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Event write-up naming the speakers',
        source_name: 'EPIC Connector post',
        url: 'https://www.linkedin.com/posts/epic-connector_epicconnector-google-ai-activity-7405055177067593728-uVLy',
        source_type: 'third_party',
        note: 'A public event write-up lists “Lee Sonic, CEO of CometAPI” among the leaders who took part.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Lee Sonic — CometAPI',
        source_name: 'LinkedIn profile',
        url: 'https://sg.linkedin.com/in/lee-sonic-220155121',
        source_type: 'profile',
        note: 'Profile headline gives Lee Sonic as CEO of CometAPI.',
        strength: 'supported',
        opened: false,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Company profile',
        source_name: 'LinkedIn company page',
        url: 'https://www.linkedin.com/company/cometapi',
        source_type: 'third_party',
        note: 'Profile gives CometAPI as a Hong Kong company of 11–50 people, founded 2024. No registered legal name is given.',
        strength: 'supported',
        opened: false,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms of Service',
        source_name: 'Provider Terms',
        url: 'https://www.cometapi.com/terms-of-service/',
        source_type: 'first_party',
        note: 'Governed by the laws of Hong Kong. Gives support and partner contact addresses but names no company.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'github',
        label: 'GitHub organisation',
        source_name: 'GitHub API record',
        url: 'https://api.github.com/users/CometAPI-dev',
        source_type: 'profile',
        note: 'Organisation account for CometAPI, linked from the provider’s own markup. Created 7 August 2025.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Official accounts',
        source_name: 'Provider structured data',
        url: 'https://www.cometapi.com/',
        source_type: 'first_party',
        note: 'The homepage’s own markup links its GitHub organisation, X account, LinkedIn company page and Discord.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'CometAPI publishes the widest official presence in the index: documentation, pricing, terms, privacy, support, a GitHub organisation and linked company accounts. A public event write-up and a profile headline both identify Lee Sonic as its CEO, and the company page CometAPI links from its own site describes a Hong Kong company of 11–50 people. No page on the provider’s own site names a person or a registered company.',
    unknowns: [
      'The CEO attribution rests on a third-party event write-up and a profile headline. CometAPI’s own site names no person.',
      'No registered company name appears in the Terms, the Privacy policy or anywhere else on the site.',
      'The company profile gives a founding year of 2024, while a biography that search engines still attribute to the About page says January 2025. That biography is no longer on the live page and was not used.',
    ],
  },
  {
    provider_id: 'relaygpu',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'likely',
      public_name: 'Ramazan Fatih Karadeniz',
      role: 'Founder, OpenGPU Network — RelayGPU’s stated parent',
      profile_urls: ['https://tr.linkedin.com/in/ramazan-fatih-karadeniz'],
      strength: 'supported',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'OpenGPU Management S.à r.l.',
      jurisdiction: 'Luxembourg',
      registration_reference: null,
      strength: 'strong',
    },
    official_presence: {
      website: 'https://relaygpu.com/',
      docs: 'https://docs.relaygpu.com',
      pricing: 'https://relaygpu.com/pricing',
      terms: 'https://relaygpu.com/legals/terms',
      privacy: 'https://relaygpu.com/legals/privacy',
      github: 'https://github.com/opengpunetwork',
      x: 'https://x.com/openGPUnetwork',
      linkedin: 'https://www.linkedin.com/company/opengpu',
      chat: null,
      support: 'mailto:info@relaygpu.com',
    },
    unreadable_surfaces: ['terms', 'privacy'],
    operating_history: 'The About page gives the operating company as incorporated in Luxembourg in 2024.',
    evidence: [
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'About page',
        source_name: 'Provider About',
        url: 'https://relaygpu.com/about',
        source_type: 'first_party',
        note: 'States RelayGPU is developed and operated by OpenGPU Management S.à r.l., incorporated in Luxembourg in 2024.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'OpenGPU Network — About',
        source_name: 'Parent network site',
        url: 'https://opengpu.network/about',
        source_type: 'first_party',
        note: 'The parent network lists relaygpu.com among its own products, under the label “Relay Gateway”.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Relay Explained',
        source_name: 'OpenGPU Network YouTube channel',
        url: 'https://www.youtube.com/@opengpunetwork',
        source_type: 'first_party',
        note: 'The parent’s own channel, linked from opengpu.network, hosts a video titled “Relay Explained | Ramazan Fatih Karadeniz”.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Account of meeting the OpenGPU founder',
        source_name: 'Public post by a third party',
        url: 'https://www.linkedin.com/posts/nataliia-radina-12344b77_why-i-amsterdam-well-at-least-sometimes-activity-7316411463596716032-6aXu',
        source_type: 'third_party',
        note: 'A public post describes meeting “the founder of OpenGPU Ramazan Fatih Karadeniz”.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Ramazan Fatih Karadeniz',
        source_name: 'LinkedIn profile',
        url: 'https://tr.linkedin.com/in/ramazan-fatih-karadeniz',
        source_type: 'profile',
        note: 'Profile headline gives him as Founder of OpenGPU Foundation. It does not mention RelayGPU.',
        strength: 'supported',
        opened: false,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'github',
        label: 'OpenGPU Network account',
        source_name: 'GitHub API record',
        url: 'https://api.github.com/users/OpenGPUNetwork',
        source_type: 'profile',
        note: 'Account names OpenGPU Network, links opengpu.network and gives its company as OpenGPU Foundation.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'RelayGPU states that it is developed and operated by OpenGPU Management S.à r.l. in Luxembourg, and the OpenGPU Network site lists relaygpu.com among its own products as the “Relay Gateway”. Ramazan Fatih Karadeniz is publicly identified as founder of the OpenGPU parent, and the parent’s own channel hosts a video presenting him explaining Relay. No source describes him as operating RelayGPU itself.',
    unknowns: [
      'The named person’s role is with the OpenGPU parent. No source ties him personally to running the RelayGPU product.',
      'No Luxembourg registry record or company number was retrievable, so the stated company is unconfirmed.',
      'The linked code account gives its company as “OpenGPU Foundation”, which differs from the stated legal name.',
      'The terms and privacy pages are served but render their text in the browser, so their wording could not be read.',
    ],
  },
  {
    provider_id: 'surplus-intelligence',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'identified',
      public_name: 'Mac Strelioff',
      role: 'Builder and operator',
      profile_urls: ['https://farcaster.xyz/macs', 'https://x.com/mac_eth'],
      strength: 'strong',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'Surplus Intelligence LLC',
      jurisdiction: 'Wyoming, United States',
      registration_reference: null,
      strength: 'strong',
    },
    official_presence: {
      website: 'https://www.surplusintelligence.ai/',
      docs: 'https://www.surplusintelligence.ai/docs',
      pricing: 'https://www.surplusintelligence.ai/markets',
      terms: 'https://www.surplusintelligence.ai/terms-of-service',
      privacy: 'https://www.surplusintelligence.ai/privacy-policy',
      github: null,
      x: 'https://x.com/AskSurplus',
      linkedin: null,
      chat: 'https://discord.gg/uWUXc32JqA',
      support: 'mailto:support@surplusintelligence.ai',
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Mac Strelioff',
        source_name: 'Farcaster identity record',
        url: 'https://api.farcaster.xyz/v2/user-by-username?username=macs',
        source_type: 'profile',
        note: 'Public identity record gives the name Mac Strelioff, a bio reading “building Surplus Intelligence”, and a linked, unexpired X account mac_eth.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Posts about the product',
        source_name: 'Farcaster posts',
        url: 'https://farcaster.xyz/macs',
        source_type: 'profile',
        note: 'Mac Strelioff posts in the first person about fixing and testing the Surplus Intelligence application.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Buy page',
        source_name: 'Provider site',
        url: 'https://www.surplusintelligence.ai/buy',
        source_type: 'first_party',
        note: 'Footer gives Surplus Intelligence LLC at a Sheridan, Wyoming address, alongside “Surplus Intelligence Corporation”.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Terms of Service',
        source_name: 'Provider Terms',
        url: 'https://www.surplusintelligence.ai/terms-of-service',
        source_type: 'first_party',
        note: 'Names Surplus Intelligence LLC as the operator and merchant of record for inference purchases.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Official accounts',
        source_name: 'Provider site',
        url: 'https://www.surplusintelligence.ai/',
        source_type: 'first_party',
        note: 'The homepage links exactly two accounts of its own: the X account @AskSurplus and a Discord invite.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'Mac Strelioff publicly builds and operates Surplus Intelligence: his public identity record carries the name, a bio describing the marketplace, and a linked X account, and he posts in the first person about working on the product. Terms, Privacy and the buy page name Surplus Intelligence LLC at a Wyoming address as the operating company.',
    unknowns: [
      'No Wyoming registry record was retrievable — the state filing search is behind a CAPTCHA — so the stated company is unconfirmed.',
      'The provider’s own site links only its brand account; the operator’s identity comes from his own public profile rather than from the site.',
      'The site footer uses both “Surplus Intelligence Corporation” and “Surplus Intelligence LLC”.',
    ],
  },
  {
    provider_id: 'boundlessapi',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'Boundless Intelligence Labs, Inc.',
      jurisdiction: 'Delaware, United States',
      registration_reference: null,
      strength: 'strong',
    },
    official_presence: {
      website: 'https://www.boundlessapi.com/',
      docs: 'https://www.boundlessapi.com/en/quickstart.html',
      pricing: 'https://www.boundlessapi.com/en/price.html',
      terms: 'https://www.boundlessapi.com/en/terms.html',
      privacy: 'https://www.boundlessapi.com/en/privacy-policy.html',
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://discord.gg/8JV6ngQeH',
      support: 'https://www.boundlessapi.com/en/contact.html',
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Terms of Service',
        source_name: 'Provider Terms',
        url: 'https://www.boundlessapi.com/en/terms.html',
        source_type: 'first_party',
        note: 'States the agreement is with Boundless Intelligence Labs, Inc., a Delaware corporation.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Data policy',
        source_name: 'Provider data policy',
        url: 'https://www.boundlessapi.com/en/data-policy.html',
        source_type: 'first_party',
        note: 'Gives the billing entity as Boundless Intelligence Labs, Inc. (Delaware).',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Quickstart documentation',
        source_name: 'Provider docs',
        url: 'https://www.boundlessapi.com/en/quickstart.html',
        source_type: 'first_party',
        note: 'Documents the OpenAI-compatible endpoints. No operator is named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'support',
        label: 'Contact page',
        source_name: 'Provider contact',
        url: 'https://www.boundlessapi.com/en/contact.html',
        source_type: 'first_party',
        note: 'Repeats the Delaware company name and gives a mailing address. No role is stated for any person.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'Terms, the data policy and the contact page all name Boundless Intelligence Labs, Inc., a Delaware corporation, as the operating and billing entity. We could not retrieve an independent registration record, so the company is recorded as provider-stated. No person is identified in a stated role on the provider’s own surfaces.',
    unknowns: [
      'No independent Delaware registration record was retrievable, so the stated company is unconfirmed.',
      'No founder, officer or team member is named in a stated role. The contact page carries a personal name only inside a mailing address, which is not an operator claim and is not published here.',
      'The only public account linked is a Discord invite; there is no code, X or company profile.',
      'The data-processing agreement that repeats the company name is marked “draft — for attorney review only”.',
    ],
  },
  {
    provider_id: 'worldgate',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://worldgateapi.com/',
      docs: 'https://worldgateapi.com/guides',
      pricing: 'https://worldgateapi.com/pricing',
      terms: 'https://worldgateapi.com/terms',
      privacy: 'https://worldgateapi.com/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: 'https://worldgateapi.com/support',
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://worldgateapi.com/terms',
        source_type: 'first_party',
        note: 'Defines “WorldGate” as the operator, under Malaysian law with Kuala Lumpur jurisdiction. No company is named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'website',
        label: 'About page',
        source_name: 'Provider About',
        url: 'https://worldgateapi.com/about-worldgate',
        source_type: 'first_party',
        note: 'Describes an independent gateway and disclaims affiliation with the model makers. Names no person.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'support',
        label: 'Support',
        source_name: 'Provider support page',
        url: 'https://worldgateapi.com/support',
        source_type: 'first_party',
        note: 'Published support route with a first-party contact address.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'WorldGate publishes guides, pricing, terms, privacy and a support route, and its Terms place the service under Malaysian law with Kuala Lumpur jurisdiction. No company name appears anywhere, the page titled “Company” is an enquiry form, and the site links no social or code account.',
    unknowns: [
      'No company name is disclosed; the Terms give a governing jurisdiction but not a registered entity.',
      'No founder, officer or team member is named on any page of the site.',
      'The site links no social, code or company account, so no official account could be confirmed as its own.',
    ],
  },
  {
    provider_id: 'derouter',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://derouter.ai/',
      docs: 'https://derouter.ai/docs',
      pricing: 'https://derouter.ai/pricing',
      terms: 'https://derouter.ai/terms',
      privacy: 'https://derouter.ai/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://t.me/derouter_ai',
      support: 'mailto:support@derouter.ai',
    },
    operating_history: 'The provider’s FAQ states stable operation since 2025.',
    evidence: [
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Homepage and FAQ',
        source_name: 'Provider site',
        url: 'https://derouter.ai/',
        source_type: 'first_party',
        note: 'Describes a Claude and GPT API provider and states stable operation since 2025. Names no company or person.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://derouter.ai/terms',
        source_type: 'first_party',
        note: 'Describes prepaid model access and gives a support address. No entity, operator or jurisdiction.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Telegram group',
        source_name: 'Telegram',
        url: 'https://t.me/derouter_ai',
        source_type: 'first_party',
        note: 'Public group linked from the site, titled “DeRouter AI 交流群”. No operator is named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'derouter.ai publishes documentation, pricing, terms and a privacy policy, and answers on a public Telegram group. None of those pages names a company, an operating individual or a jurisdiction. Its FAQ states the service has run since 2025.',
    unknowns: [
      'No company, operator or jurisdiction is disclosed on any page, including Terms and Privacy.',
      'No social or code account beyond the Telegram group is linked.',
      'No public connection was found between this provider and the separately branded derouter.network and github.com/derouter projects, which describe a decentralised subscription marketplace.',
    ],
  },
  {
    provider_id: 'getgoapi',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://getgoapi.com/',
      docs: 'https://getgoapi.com/docs',
      pricing: 'https://getgoapi.com/en/pricing',
      terms: 'https://getgoapi.com/en/terms',
      privacy: 'https://getgoapi.com/en/privacy',
      github: 'https://github.com/getgoapi',
      x: null,
      linkedin: null,
      chat: null,
      support: 'https://getgoapi.com/en/contact',
    },
    operating_history: 'The linked GitHub account was created 16 August 2021, the oldest public trace of any provider in the index.',
    evidence: [
      {
        claim_type: 'presence',
        category: 'github',
        label: 'GitHub account',
        source_name: 'GitHub API record',
        url: 'https://api.github.com/users/getgoapi',
        source_type: 'profile',
        note: 'Account linked from the provider’s footer, holding gateway and proxy repositories. Created 16 August 2021.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://getgoapi.com/en/terms',
        source_type: 'first_party',
        note: 'Governing law is “the jurisdiction in which GetGoAPI operates”, which is left unnamed.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'privacy',
        label: 'Privacy policy',
        source_name: 'Provider Privacy',
        url: 'https://getgoapi.com/en/privacy',
        source_type: 'first_party',
        note: 'References GDPR and CCPA compliance but names no company, address or operator.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'support',
        label: 'Contact page',
        source_name: 'Provider contact',
        url: 'https://getgoapi.com/en/contact',
        source_type: 'first_party',
        note: 'Published contact route for account and billing questions.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'GetGoAPI publishes documentation, pricing, terms, privacy, a contact route and a GitHub account whose repositories match the product. That account dates from 2021, making it the oldest public trace of any provider here. None of the pages names a company, a jurisdiction or an individual.',
    unknowns: [
      'No company name, address or jurisdiction is disclosed, including in the Terms.',
      'No founder, officer or team member is named, and the GitHub account lists no public owner.',
      'The LinkedIn company page linked from the footer returns 404, so it is not recorded as a channel.',
    ],
  },
  {
    provider_id: 'llmsrelay',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://llmsrelay.com/',
      docs: 'https://llmsrelay.com/docs/getting-started/introduction/',
      pricing: 'https://llmsrelay.com/plans/',
      terms: 'https://llmsrelay.com/terms-and-conditions/',
      privacy: 'https://llmsrelay.com/legal/privacy/',
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://telegram.me/claudestorestore',
      support: 'https://llmsrelay.com/contacts/',
    },
    operating_history: 'Terms carry an effective date of 1 May 2026.',
    evidence: [
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Public offer',
        source_name: 'Provider legal offer',
        url: 'https://llmsrelay.com/legal/offer/',
        source_type: 'first_party',
        note: 'States the offer is made by “an individual operating the website”, who is not named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms and conditions',
        source_name: 'Provider Terms',
        url: 'https://llmsrelay.com/terms-and-conditions/',
        source_type: 'first_party',
        note: 'Refers to “LLMsRelay and its operators” and an unnamed jurisdiction of registration.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://llmsrelay.com/docs/getting-started/introduction/',
        source_type: 'first_party',
        note: 'Documents the relay API and the prepaid usage packs its pricing is based on.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Telegram channel',
        source_name: 'Telegram',
        url: 'https://telegram.me/claudestorestore',
        source_type: 'first_party',
        note: 'Channel linked from the site as its contact point. Contacts there are given as handles only.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'LLMsRelay publishes documentation, plans, terms, a privacy policy and a public offer. The offer states plainly that the service is run by an individual rather than a company — and does not name that individual. Contact runs through a Telegram channel where people are identified by handle.',
    unknowns: [
      'The operator is described by the provider as an individual but is never named.',
      'No company and no jurisdiction of registration is given, although the Terms refer to one.',
      'The about page is written under an editorial persona rather than by a named person.',
    ],
  },
  {
    provider_id: 'frugalrelay',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://frugalrelay.me/',
      docs: 'https://docs.frugalrelay.me/',
      pricing: 'https://frugalrelay.me/pricing',
      terms: 'https://frugalrelay.me/terms',
      privacy: 'https://frugalrelay.me/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: 'https://frugalrelay.me/contact',
    },
    unreadable_surfaces: ['terms', 'privacy'],
    operating_history: 'A provider blog post dated 16 May 2026 is the earliest public trace retrieved.',
    evidence: [
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Site structured data',
        source_name: 'Provider site',
        url: 'https://frugalrelay.me/',
        source_type: 'first_party',
        note: 'Organisation markup carries the brand name and a support address, with no legal name.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms of Service',
        source_name: 'Provider Terms',
        url: 'https://frugalrelay.me/terms',
        source_type: 'first_party',
        note: 'Served under its own title, but the text renders in the browser and could not be read.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://docs.frugalrelay.me/',
        source_type: 'first_party',
        note: 'Documents the gateway API whose public pricing endpoint the index reads.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'history',
        category: 'website',
        label: 'Blog post',
        source_name: 'Provider blog',
        url: 'https://docs.frugalrelay.me/blog/slash-ai-costs-frugal-relay/',
        source_type: 'first_party',
        note: 'Post dated 16 May 2026, signed “Frugal Relay Team” rather than by a named person.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'Frugal Relay publishes documentation, pricing, a contact route and terms and privacy pages, and signs its blog as “Frugal Relay Team”. The legal pages are served but render their text in the browser, so their wording could not be read, and no company or individual is named anywhere we could read.',
    unknowns: [
      'Terms and privacy text could not be retrieved, so whether they name a company is unresolved.',
      'No company, person, address or jurisdiction is disclosed in any retrievable content.',
      'No social or code account is linked from the site.',
    ],
  },
  {
    provider_id: 'omniakey',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://omniakey.com/',
      docs: 'https://docs.omniakey.com/en/introduction',
      pricing: 'https://omniakey.com/pricing',
      terms: 'https://omniakey.com/en/terms',
      privacy: 'https://omniakey.com/en/privacy',
      github: null,
      x: 'https://x.com/OmniaKey',
      linkedin: null,
      chat: 'https://t.me/OmniaKey',
      support: 'mailto:support@omniakey.com',
    },
    operating_history: 'The domain was registered on 27 February 2026.',
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Homepage FAQ',
        source_name: 'Provider site',
        url: 'https://omniakey.com/',
        source_type: 'first_party',
        note: 'Answers who is behind OmniaKey with “a small team of developers”, and supplies no names.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://omniakey.com/en/terms',
        source_type: 'first_party',
        note: 'Says the service is operated by “the OmniaKey team”, under Hong Kong SAR law with HKIAC arbitration.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://docs.omniakey.com/en/introduction',
        source_type: 'first_party',
        note: 'Hosted API documentation for the OpenAI-compatible catalogue.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Official accounts',
        source_name: 'Provider site',
        url: 'https://omniakey.com/',
        source_type: 'first_party',
        note: 'Links its own X account and a Telegram channel titled “OmniaKey Team”.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'OmniaKey publishes documentation, pricing, terms, a privacy policy, a support address and linked accounts, and its Terms place the service under Hong Kong SAR law with HKIAC arbitration. The site describes its operators as a small team of developers and names none of them.',
    unknowns: [
      'No company name is disclosed; the Terms give a governing jurisdiction but not a registered entity.',
      'No individual is named, and there is no about or team page.',
      'The site describes “a small team of developers” without any way to check who they are.',
    ],
  },
  {
    provider_id: 'aitransx',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://aitransx.com/',
      docs: 'https://aitransx.com/en/docs',
      pricing: 'https://aitransx.com/en/pricing',
      terms: 'https://aitransx.com/en/terms',
      privacy: 'https://aitransx.com/en/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: 'mailto:support@aitransx.com',
    },
    operating_history: 'Terms and privacy carry an effective date of 18 July 2026.',
    evidence: [
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://aitransx.com/en/terms',
        source_type: 'first_party',
        note: 'Gives the contracting party as “AITransX”, which is the brand rather than a company name.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Privacy policy',
        source_name: 'Provider Privacy',
        url: 'https://aitransx.com/en/privacy',
        source_type: 'first_party',
        note: 'Repeats the same brand as operator, with no company, address or jurisdiction.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://aitransx.com/en/docs',
        source_type: 'first_party',
        note: 'Gives the API base URL, authentication and model instructions for the catalogue the index reads.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'AITransX publishes documentation, pricing, terms and a privacy policy, and both legal pages give the contracting party as the brand name rather than a company. It links no social or code account, and no individual is named.',
    unknowns: [
      'No company name, address or jurisdiction is disclosed; the Terms name only the brand as the counterparty.',
      'No founder or team member is named, and about and contact paths return 404.',
      'No social or code account is linked anywhere on the site.',
    ],
  },
  {
    provider_id: 'llmrelay-dev',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://llmrelay.dev/',
      docs: 'https://llmrelay.dev/docs/',
      pricing: 'https://llmrelay.dev/pricing/',
      terms: 'https://llmrelay.dev/terms/',
      privacy: 'https://llmrelay.dev/privacy/',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: 'mailto:support@llmrelay.dev',
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms',
        source_name: 'Provider Terms',
        url: 'https://llmrelay.dev/terms/',
        source_type: 'first_party',
        note: 'Describes llmrelay as an OpenAI-compatible relay. No company or person is named.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'privacy',
        label: 'Privacy policy',
        source_name: 'Provider Privacy',
        url: 'https://llmrelay.dev/privacy/',
        source_type: 'first_party',
        note: 'Names its processors, including payment and mail providers, but no operating company.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://llmrelay.dev/docs/',
        source_type: 'first_party',
        note: 'Covers API setup and model access for the published endpoint.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Affiliate disclosure',
        source_name: 'Provider disclosure',
        url: 'https://llmrelay.dev/disclosure/',
        source_type: 'first_party',
        note: 'Discloses that the site carries affiliate links and runs a referral programme.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'llmrelay publishes documentation, pricing, terms, a privacy policy, an acceptable-use policy and an affiliate disclosure. The privacy policy names its own processors but no operating company, and no page names a person or a company.',
    unknowns: [
      'No company, person, address or jurisdiction is disclosed on any page.',
      'There is no about page; those paths serve the homepage instead.',
      'A GitHub project of a similar name is a separate self-hosted gateway and is not this provider’s code account.',
    ],
  },
  {
    provider_id: 'relay-fast',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://relay.fast/',
      docs: 'https://relay.fast/docs',
      pricing: 'https://relay.fast/api-pricing',
      terms: 'https://relay.fast/terms',
      privacy: 'https://relay.fast/privacy',
      github: null,
      x: 'https://x.com/relayfast_ai',
      linkedin: null,
      chat: 'https://t.me/relayfast_ai',
      support: 'https://relay.fast/status',
    },
    unreadable_surfaces: ['terms', 'privacy'],
    operating_history: 'Site scripts still resolve two earlier brand names for the same service.',
    evidence: [
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Machine-readable site summary',
        source_name: 'Provider llms.txt',
        url: 'https://relay.fast/llms.txt',
        source_type: 'first_party',
        note: 'Describes a pay-as-you-go gateway and indexes the docs, pricing, status, security and retention pages.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Site structured data',
        source_name: 'Provider site',
        url: 'https://relay.fast/',
        source_type: 'first_party',
        note: 'Organisation markup carries the brand name only, with no legal name, address or contact point.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'social',
        label: 'Official accounts',
        source_name: 'Provider structured data',
        url: 'https://relay.fast/terms',
        source_type: 'first_party',
        note: 'Markup lists the provider’s X, Telegram, TikTok and YouTube channels as its own.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'history',
        category: 'website',
        label: 'Legacy brand references',
        source_name: 'Provider page script',
        url: 'https://relay.fast/terms',
        source_type: 'first_party',
        note: 'An inline script maps two earlier names, “New API” and “router.cheap”, onto the current brand.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'relay.fast publishes documentation, pricing, a status page, terms, a privacy policy and several linked accounts. Its structured data carries the brand name only, and the terms and privacy text renders in the browser, so neither could be read to check for a company.',
    unknowns: [
      'Terms and privacy text could not be retrieved, so whether they name a company is unresolved.',
      'No company, person or jurisdiction appears in any retrievable page content.',
      'Site scripts reference two earlier brand names for the same service, and that history is not explained publicly.',
    ],
  },
  {
    provider_id: 'zrelay',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'not_found',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://zrelay.net/',
      docs: 'https://zrelay.net/docs.html',
      pricing: 'https://zrelay.net/prices.html',
      terms: null,
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://t.me/zrelay_net',
      support: 'https://t.me/zrelay_net',
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Homepage',
        source_name: 'Provider site',
        url: 'https://zrelay.net/',
        source_type: 'first_party',
        note: 'States the service needs no account, email or identity check, and takes payment in Bitcoin.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Prices',
        source_name: 'Provider pricing page',
        url: 'https://zrelay.net/prices.html',
        source_type: 'first_party',
        note: 'Publishes prepaid credit tiers and a stated twelve-month refund coverage window.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://zrelay.net/docs.html',
        source_type: 'first_party',
        note: 'Documents endpoints for the Claude, GPT and Grok wire formats.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'support',
        label: 'Telegram support',
        source_name: 'Telegram channel',
        url: 'https://t.me/zrelay_net',
        source_type: 'first_party',
        note: 'The site gives this channel and stated support hours as its only contact route. The channel is titled “Zrelay”.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'Zrelay publishes a price table, documentation and a Telegram support channel, and states that it deliberately collects no account or identity data. It publishes no terms of service and no privacy policy, and names no company or individual.',
    unknowns: [
      'No terms of service and no privacy policy are published; those paths return 404.',
      'No company, person, address or jurisdiction is disclosed anywhere on the site.',
      'The only contact route is a Telegram channel under the brand name; no individual is identified there.',
    ],
  },
  {
    provider_id: 'relay-ai',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED,
    founder_operator: {
      status: 'unknown',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'unknown',
      name: null,
      jurisdiction: null,
      registration_reference: null,
      strength: 'none',
    },
    official_presence: {
      website: 'https://relay-ai.org/',
      docs: null,
      pricing: 'https://relay-ai.org/',
      terms: null,
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: 'https://t.me/relayaiorg',
      support: 'https://t.me/relayaiorg',
    },
    unreadable_surfaces: ['website'],
    operating_history: null,
    evidence: [
      {
        claim_type: 'presence',
        category: 'website',
        label: 'Homepage',
        source_name: 'Provider site',
        url: 'https://relay-ai.org/',
        source_type: 'first_party',
        note: 'Renders entirely in the browser; read through a text proxy it describes a unified API with several provider routes.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
      {
        claim_type: 'presence',
        category: 'support',
        label: 'Telegram channel',
        source_name: 'Application bundle',
        url: 'https://t.me/relayaiorg',
        source_type: 'first_party',
        note: 'The only contact route referenced by the application the site loads in the browser.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED,
      },
    ],
    summary:
      'Relay serves a browser-rendered application with no retrievable about, terms, privacy or documentation pages. The only contact route we could establish is a Telegram channel referenced by the application itself. No company or individual is identified.',
    unknowns: [
      'No terms, privacy policy, documentation or about page could be retrieved.',
      'No company, person, address or jurisdiction is disclosed.',
      'Because the site renders in the browser, published text may exist that this review could not read.',
    ],
  },
  {
    provider_id: 'vercel-ai-gateway',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [
      {
        name: 'Walter Korman',
        role: 'Author, AI Gateway general-availability announcement',
        url: 'https://vercel.com/blog/ai-gateway-is-now-generally-available',
        strength: 'supported',
      },
      {
        name: 'Harpreet Arora',
        role: 'Author, AI Gateway general-availability announcement',
        url: 'https://vercel.com/blog/ai-gateway-is-now-generally-available',
        strength: 'supported',
      },
    ],
    legal_entity: {
      status: 'self_disclosed',
      name: 'Vercel Inc.',
      jurisdiction: null,
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://vercel.com/ai-gateway',
      docs: 'https://vercel.com/docs/ai-gateway',
      pricing: 'https://vercel.com/ai-gateway/models',
      terms: 'https://vercel.com/legal/terms',
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'terms',
        label: 'Terms of Service',
        source_name: 'Provider terms',
        url: 'https://vercel.com/legal/terms',
        source_type: 'first_party',
        note: 'Names Vercel Inc. as the contracting party and gives San Francisco County courts as the exclusive jurisdiction.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'team',
        category: 'founder',
        label: 'AI Gateway is now generally available',
        source_name: 'Provider blog',
        url: 'https://vercel.com/blog/ai-gateway-is-now-generally-available',
        source_type: 'first_party',
        note: 'Walter Korman and Harpreet Arora are bylined as the authors of the product announcement; no job titles are given.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Model catalogue',
        source_name: 'Provider pricing API',
        url: 'https://ai-gateway.vercel.sh/v1/models',
        source_type: 'first_party',
        note: 'Public unauthenticated JSON listing every model with per-token input and output prices.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'AI Gateway pricing docs',
        source_name: 'Provider docs',
        url: 'https://vercel.com/docs/ai-gateway/pricing',
        source_type: 'first_party',
        note: 'States that the gateway charges no markup and no platform fee on tokens and bills pay-as-you-go against purchased credits.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'Vercel Inc. is named as the contracting party in the platform terms, and the AI Gateway general-availability announcement carries two named authors. No leadership page could be read: the leadership route returns a sign-in page and the about page lists investors rather than staff.',
    unknowns: [
      'No job titles are published for the two named announcement authors.',
      'No officer or executive is named on any Vercel page this review could open.',
      'No company registration number or state of incorporation is published in the terms.',
    ],
  },
  {
    provider_id: 'zenmux',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_COMPLETION,
    founder_operator: {
      status: 'likely',
      public_name: 'Ming Jia',
      // The profile gives ZenMux as the current company but does not expose a
      // title without signing in, so no role is published here.
      role: null,
      profile_urls: ['https://www.linkedin.com/in/ming-jia-0110a71a'],
      strength: 'supported',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'AI Force Singapore Pte. Ltd.',
      jurisdiction: 'Singapore',
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://zenmux.ai/',
      docs: 'https://zenmux.ai/docs/',
      pricing: 'https://zenmux.ai/api/v1/models',
      terms: 'https://zenmux.ai/docs/terms-of-service.html',
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'terms',
        label: 'Terms of Service',
        source_name: 'Provider docs',
        url: 'https://zenmux.ai/docs/terms-of-service.html',
        source_type: 'first_party',
        note: 'States the service is owned and operated by AI Force Singapore Pte. Ltd. and governed by the laws of Singapore.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Ming Jia',
        source_name: 'LinkedIn profile',
        url: 'https://www.linkedin.com/in/ming-jia-0110a71a',
        source_type: 'profile',
        note: 'The public preview of Ming Jia’s profile gives ZenMux as the current company; the role itself is not visible without signing in.',
        strength: 'supported',
        opened: false,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Model catalogue',
        source_name: 'Provider pricing API',
        url: 'https://zenmux.ai/api/v1/models',
        source_type: 'first_party',
        note: 'Public unauthenticated JSON giving prompt and completion prices per million tokens in USD, with long-context conditions.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Billing transparency',
        source_name: 'Provider docs',
        url: 'https://zenmux.ai/docs/guide/observability/pricing.html',
        source_type: 'first_party',
        note: 'Enumerates the billing items metered per call; no percentage service fee appears among them.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'The ZenMux terms of service name AI Force Singapore Pte. Ltd. as the operating company under Singapore law, and the same name appears in the site footer. Ming Jia’s public professional profile gives ZenMux as his current company, though no individual is named anywhere on the site itself.',
    unknowns: [
      'No individual is named on any ZenMux page; the operator association comes from a professional profile, not from the provider.',
      'The profile does not expose a job title without signing in, so no role is published here.',
      'The blog footer renders a different company name, NexaMind Singapore Pte. Ltd., than the terms of service and the site footer.',
      'No company registration number is published, so the Singapore entity could not be pointed at a registry record.',
    ],
  },
  {
    provider_id: 'atlas-cloud',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'identified',
      public_name: 'Jerry Tang',
      role: 'Founder & CEO',
      profile_urls: ['https://atlascloud.ai/about'],
      strength: 'strong',
    },
    other_public_people: [
      { name: 'Xuejun Tao', role: 'CTO', url: 'https://atlascloud.ai/about', strength: 'strong' },
      { name: 'Sanket Shah', role: 'CFO', url: 'https://atlascloud.ai/about', strength: 'strong' },
      {
        name: 'Gary Ji',
        role: 'Head of Engineering',
        url: 'https://atlascloud.ai/about',
        strength: 'strong',
      },
    ],
    legal_entity: {
      status: 'self_disclosed',
      name: 'ATLAS CLOUD AI INC.',
      jurisdiction: 'New York, United States',
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://atlascloud.ai/',
      docs: 'https://www.atlascloud.ai/docs',
      pricing: 'https://api.atlascloud.ai/v1/models',
      terms: null,
      privacy: 'https://atlascloud.ai/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'founder',
        category: 'founder',
        label: 'About page',
        source_name: 'Provider site',
        url: 'https://atlascloud.ai/about',
        source_type: 'first_party',
        note: 'Names Jerry Tang as Founder & CEO alongside eight further named staff and one advisor, each with a stated role.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'entity',
        category: 'privacy',
        label: 'Legal terms',
        source_name: 'Provider legal page',
        url: 'https://atlascloud.ai/privacy',
        source_type: 'first_party',
        note: 'Gives ATLAS CLOUD AI INC. at 1540 Broadway, New York, and New York as the governing law.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Model catalogue',
        source_name: 'Provider pricing API',
        url: 'https://api.atlascloud.ai/v1/models',
        source_type: 'first_party',
        note: 'Public unauthenticated JSON giving per-token prices and the serving precision of each route.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'Atlas Cloud publishes a named leadership team on its own about page, led by Jerry Tang as Founder & CEO, and its legal pages give ATLAS CLOUD AI INC. in New York as the operating company. Its model catalogue is public JSON and states the serving precision of each route.',
    unknowns: [
      'No company registration number is published, so the New York entity could not be pointed at a registry record.',
      'The canonical terms-of-service URLs return 404, so the full contract text could not be read.',
    ],
  },
  {
    provider_id: 'gptproto',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [
      {
        name: 'Sammi Cen',
        role: 'Business Development',
        url: 'https://natlawreview.com/press-releases/gpt-proto-now-fully-supports-gpt-image-2',
        strength: 'supported',
      },
    ],
    legal_entity: {
      status: 'verified',
      name: 'Talent Tech Global Limited',
      jurisdiction: 'Hong Kong',
      registration_reference: 'https://www.cr.gov.hk/docs/wrpt/wk_new%26changednamecoys_20251222.pdf',
      strength: 'strong',
    },
    official_presence: {
      website: 'https://gptproto.com/',
      docs: 'https://docs.gptproto.com/',
      pricing: 'https://gptproto.com/model',
      terms: 'https://gptproto.com/terms-of-service',
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'terms',
        label: 'Terms of Use',
        source_name: 'Provider terms',
        url: 'https://gptproto.com/terms-of-service',
        source_type: 'first_party',
        note: 'Gives Talent Tech Global Limited, Hong Kong, with a certificate number and a Tsim Sha Tsui registered address.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Hong Kong Companies Registry weekly gazette',
        source_name: 'Hong Kong Companies Registry',
        url: 'https://www.cr.gov.hk/docs/wrpt/wk_new%26changednamecoys_20251222.pdf',
        source_type: 'registry',
        note: 'The registry’s new-incorporations list records Talent Tech Global Limited, business registration number 79462435, incorporated 23-12-2025; the number matches the certificate GPTProto publishes.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'team',
        category: 'founder',
        label: 'GPT Proto product press release',
        source_name: 'National Law Review',
        url: 'https://natlawreview.com/press-releases/gpt-proto-now-fully-supports-gpt-image-2',
        source_type: 'third_party',
        note: 'Names Sammi Cen, Business Development, as the media contact for Talent Tech Global Limited.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Model catalogue',
        source_name: 'Provider pricing page',
        url: 'https://gptproto.com/model',
        source_type: 'first_party',
        note: 'Server-rendered catalogue giving one USD input and output rate per million tokens for each model.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'GPTProto names Talent Tech Global Limited of Hong Kong on its about and terms pages, with a certificate number and registered address. The Hong Kong Companies Registry’s own weekly gazette records that company under business registration number 79462435, incorporated 23 December 2025, and the number matches the certificate the provider publishes. No founder or officer is named on the provider’s own pages.',
    unknowns: [
      'No founder or officer is named on any GPTProto page, and leadership descriptions differ between third-party write-ups.',
      'A business-development contact appears in a third-party press release; that release could not be re-opened in the latest pass, so the person is recorded but not re-confirmed.',
      'The provider’s own catalogue states comparison prices that do not match current first-party maker pricing, so none of them are ingested.',
    ],
  },
  {
    provider_id: 'evolink',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'identified',
      public_name: 'Jessie',
      role: 'COO',
      profile_urls: ['https://evolink.ai/en/blog/glm-5-3-release'],
      strength: 'supported',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'EVO GLOBAL TECHNOLOGIES LIMITED',
      jurisdiction: 'Hong Kong',
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://evolink.ai/',
      docs: 'https://evolink.ai/docs',
      pricing: 'https://evolink.ai/pricing',
      terms: 'https://evolink.ai/terms',
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: 'Founded 2025 per the provider’s about page.',
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Provider blog bylines',
        source_name: 'Provider blog',
        url: 'https://evolink.ai/en/blog/glm-5-3-release',
        source_type: 'first_party',
        note: 'Two release posts carry the byline Jessie with the title COO; no surname is published.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'entity',
        category: 'terms',
        label: 'Terms of Service',
        source_name: 'Provider terms',
        url: 'https://evolink.ai/terms',
        source_type: 'first_party',
        note: 'Names EVO GLOBAL TECHNOLOGIES LIMITED as a company registered in Hong Kong and states that services are provided on a pre-paid basis.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Live catalogue',
        source_name: 'Provider pricing page',
        url: 'https://evolink.ai/pricing',
        source_type: 'first_party',
        note: 'Carries a dated catalogue of charged USD rates embedded in the served page, alongside a separate undiscounted reference column.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'EvoLink publishes release posts bylined Jessie, COO, and names EVO GLOBAL TECHNOLOGIES LIMITED of Hong Kong in its terms. Its pricing page carries a dated catalogue of the rates it actually charges next to an undiscounted reference column, and only the charged rate is ingested.',
    unknowns: [
      'Only a mononym is published for the COO; no surname appears on any page and none was inferred.',
      'No company registration number is published, so the Hong Kong entity could not be pointed at a registry record.',
    ],
  },
  {
    provider_id: 'ohmygpt',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'identified',
      public_name: '李宏栓',
      role: '運営責任者 (operating manager named in the Japanese commercial disclosure)',
      profile_urls: ['https://www.ohmygpt.com/scta'],
      strength: 'supported',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'DogeNet合同会社 (DogeNet GK)',
      jurisdiction: 'Japan',
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://www.ohmygpt.com/',
      docs: 'https://docs.ohmygpt.com/',
      pricing: 'https://www.ohmygpt.com/models',
      terms: 'https://www.ohmygpt.com/tos',
      privacy: 'https://www.ohmygpt.com/privacy',
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'operator',
        category: 'founder',
        label: '特定商取引法に基づく表記',
        source_name: 'Japanese commercial-transactions disclosure',
        url: 'https://www.ohmygpt.com/scta',
        source_type: 'first_party',
        note: 'The statutory disclosure names 李宏栓 as 運営責任者 and gives a Saitama registered address and telephone number.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'entity',
        category: 'terms',
        label: 'Operating entity',
        source_name: 'Japanese commercial-transactions disclosure',
        url: 'https://www.ohmygpt.com/scta',
        source_type: 'first_party',
        note: 'Gives DogeNet合同会社 as the operating entity, rendered elsewhere on the same site as DogeNet GK.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Model catalogue',
        source_name: 'Provider models page',
        url: 'https://www.ohmygpt.com/models',
        source_type: 'first_party',
        note: 'Server-rendered cards give per-million input and output rates; some routes are priced in CNY rather than USD.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'terms',
        label: 'Terms of service',
        source_name: 'Provider terms',
        url: 'https://www.ohmygpt.com/tos',
        source_type: 'first_party',
        note: 'States that account balances operate on a pay-as-you-go basis charged according to resource usage.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'OhMyGPT publishes a Japanese statutory commercial disclosure naming DogeNet合同会社 as the operating entity and 李宏栓 as its operating manager, with a registered address and telephone number. Its model catalogue prices some routes in CNY, and only the USD-priced routes are comparable here.',
    unknowns: [
      'The disclosure gives no reading for 李宏栓, so no romanisation is published here.',
      'No company registration number is published, so the Japanese entity could not be pointed at a registry record.',
      'Routes priced in CNY are not converted and therefore do not appear in the comparison.',
    ],
  },
  {
    provider_id: 'quicksilver-pro',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_COMPLETION,
    founder_operator: {
      status: 'identified',
      public_name: 'Raullen Chai',
      // The title is his own, at the organisation QuickSilver Pro says built
      // the product. No source calls him a QuickSilver Pro founder, so the role
      // names MachineFi Labs rather than the product.
      role: 'Co-founder & CEO, MachineFi Labs',
      profile_urls: ['https://www.linkedin.com/in/raullenchai', 'https://github.com/raullenchai'],
      strength: 'supported',
    },
    other_public_people: [],
    legal_entity: {
      status: 'self_disclosed',
      name: 'MachineFi Inc.',
      jurisdiction: 'Delaware, United States',
      registration_reference: null,
      strength: 'supported',
    },
    official_presence: {
      website: 'https://quicksilverpro.io/',
      docs: 'https://quicksilverpro.io/docs',
      pricing: 'https://quicksilverpro.io/pricing.json',
      terms: null,
      privacy: null,
      github: 'https://github.com/machinefi/qspro-cli',
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'website',
        label: 'Trust page',
        source_name: 'Provider site',
        url: 'https://quicksilverpro.io/trust',
        source_type: 'first_party',
        note: 'States the service "is built by the MachineFi Labs team and operated by MachineFi Inc., a Delaware corporation", and names /pricing.json as the billing source of truth.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'operator',
        category: 'founder',
        label: 'Raullen Chai',
        source_name: 'LinkedIn profile',
        url: 'https://www.linkedin.com/in/raullenchai',
        source_type: 'profile',
        note: 'Raullen Chai states he is co-founder and CEO of MachineFi Labs, the team the provider says built QuickSilver Pro.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'operator',
        category: 'github',
        label: 'qspro-cli',
        source_name: 'GitHub, machinefi organisation',
        url: 'https://github.com/machinefi/qspro-cli',
        source_type: 'first_party',
        note: 'The QuickSilver Pro command-line client is published under the machinefi organisation and described as maintained by MachineFi Inc.; Raullen Chai’s GitHub profile gives iotexproject, the organisation MachineFi Labs is linked to.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Price file',
        source_name: 'Provider pricing endpoint',
        url: 'https://quicksilverpro.io/pricing.json',
        source_type: 'first_party',
        note: 'Public JSON giving per-million input and output prices, context length and long-context tiers; the package index lists the same organisation as the publisher of its client.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
    ],
    summary:
      'QuickSilver Pro states on its own trust page that it is built by the MachineFi Labs team and operated by MachineFi Inc., a Delaware corporation, and publishes its client under the machinefi GitHub organisation. Raullen Chai states publicly that he is co-founder and CEO of MachineFi Labs. No page on QuickSilver Pro itself names an individual.',
    unknowns: [
      'No individual is named on any QuickSilver Pro page; the person is reached through the organisation the provider says built it, not through the provider directly.',
      'No source describes Raullen Chai as a founder or officer of QuickSilver Pro itself, and none is claimed here.',
      'The Delaware registration was not looked up: that registry prohibits automated queries, so the company remains provider-stated.',
    ],
  },
  {
    provider_id: 'teamorouter',
    review_status: 'reviewed',
    last_reviewed_at: REVIEWED_EXPANSION,
    founder_operator: {
      status: 'not_found',
      public_name: null,
      role: null,
      profile_urls: [],
      strength: 'none',
    },
    other_public_people: [],
    legal_entity: {
      status: 'verified',
      name: 'Teamo HK Limited',
      jurisdiction: 'Hong Kong',
      registration_reference: 'https://www.cr.gov.hk/docs/wrpt/wk_new%26changednamecoys_20260119.pdf',
      strength: 'strong',
    },
    official_presence: {
      website: 'https://teamorouter.com/',
      docs: 'https://teamorouter.com/docs',
      pricing: 'https://teamorouter.com/pricing',
      terms: null,
      privacy: null,
      github: null,
      x: null,
      linkedin: null,
      chat: null,
      support: null,
    },
    operating_history: null,
    evidence: [
      {
        claim_type: 'entity',
        category: 'website',
        label: 'About page',
        source_name: 'Provider site',
        url: 'https://teamorouter.com/about',
        source_type: 'first_party',
        note: 'The footer reads "© 2026 Teamo HK Limited. All rights reserved."; no individual is named on the page.',
        strength: 'supported',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'entity',
        category: 'entity',
        label: 'Hong Kong Companies Registry weekly gazette',
        source_name: 'Hong Kong Companies Registry',
        url: 'https://www.cr.gov.hk/docs/wrpt/wk_new%26changednamecoys_20260119.pdf',
        source_type: 'registry',
        note: 'The registry’s new-incorporations list records Teamo HK Limited, business registration number 79637383, incorporated 20-01-2026, matching the company named in the site footer.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_COMPLETION,
      },
      {
        claim_type: 'presence',
        category: 'pricing',
        label: 'Pricing table',
        source_name: 'Provider pricing page',
        url: 'https://teamorouter.com/pricing',
        source_type: 'first_party',
        note: 'Server-rendered table giving a struck-through list column and the charged rate; only the charged rate is ingested.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
      {
        claim_type: 'presence',
        category: 'docs',
        label: 'Documentation',
        source_name: 'Provider docs',
        url: 'https://teamorouter.com/docs',
        source_type: 'first_party',
        note: 'Covers authentication and integration and states that fast mode is billed at twice the standard rate.',
        strength: 'strong',
        opened: true,
        checked_at: REVIEWED_EXPANSION,
      },
    ],
    summary:
      'TeamoRouter names Teamo HK Limited in its own site footer and sells prepaid credits that do not expire. The Hong Kong Companies Registry’s own weekly gazette records that company under business registration number 79637383, incorporated 20 January 2026. No individual is named on any TeamoRouter page.',
    unknowns: [
      'No founder, officer or team member is named on any TeamoRouter page.',
      'A person reported elsewhere as having publicly announced the launch could not be confirmed: the profile refuses automated retrieval, so no individual is recorded here.',
      'A reported link to another company through a shared product name could not be corroborated: that company’s site does not mention TeamoRouter.',
    ],
  },
];

/**
 * Built with an explicit duplicate check rather than straight from `map`.
 *
 * A `Map` silently lets the last entry win, so a second record for a provider
 * would quietly replace the first — including replacing researched evidence with
 * an empty stub — and the only thing standing between that and production would
 * be remembering to run the tests. Failing at module load makes it impossible to
 * ship.
 */
export function indexRecords(
  records: ProviderVerificationRecord[],
): Map<string, ProviderVerificationRecord> {
  const byProvider = new Map<string, ProviderVerificationRecord>();
  for (const record of records) {
    if (byProvider.has(record.provider_id)) {
      throw new Error(`Duplicate provider verification record: ${record.provider_id}`);
    }
    byProvider.set(record.provider_id, record);
  }
  return byProvider;
}

export const VERIFICATION_RECORDS_BY_PROVIDER = indexRecords(VERIFICATION_RECORDS);
